### ISSUE TITLE
Nested rules 

### ISSUE THREAD

**Issue by d-Pixie** [choltreppe/parlexgen#2]
How hard would it be to support nested rules? I'm making a parser for liquid templates and it's trivial to match an entire tag: `r"\{\{[^}]*\}\}"`, but creating matching expressions for every possible content without the closing tags is impossible. And doing it with the enclosing tags is not reasonable, it's basically a token per possible tag. And that is just not possible since that can vary in length and complexity.

Right now I have to do this in two steps: First lex the entire tags, then lex those matches using a second lexer. The issue arises from the fact that the surrounding text can be anything. So I can't lex token by token outside of the actual template tags...

**Comment by choltreppe** [comment]
yea parsing html templates sucks :/
the approach of splitting into  lexing and parsing doesnt realy work out that well there.

maybe you would be better of with using `std/pegs` or [npeg](https://github.com/zevv/npeg)

but one trick that just came to mind, would be to match 'raw-text' tokens by using lookahead and lookbehind: Checking if a char before was '>' or '}' and a char after is '<' or '{'. But I dont think that my lexer-generator can do lookahead and lookbehinds (am not sure since the lexer part is based on araqs lexim). So you might need to write the lexer yourself to do that. (just write a proc with type `LexerProc` defined in parlexgen/common.nim)

**Comment by d-Pixie** [comment]
I have a simple "meta" parser:
```
makeLexer meta_lexer*[MetaToken]:
  r"\{\{[^}]*\}\}": MetaToken(kind: VARIABLE, tokens: @[], start_pos: pos, end_pos: pos + match.len - 1, result: "" )

  r"\{%[^}]*%\}": MetaToken(kind: TAG, tokens: @[], start_pos: pos, end_pos: pos + match.len - 1, result: "" )

  r"[^{]+": continue
```
That work fine for getting the blocks out of the main HTML file. But at the moment I will have to run a second lexer in each of the VARIABLE/TAG blocks, to parse the match from meta - since that is just a single, complete liquid tag:
```
# Very much a work in progress :D
makeLexer variable_lexer*[Token]:
  r"\{\{-": Token(kind: WHITESPACE_CONTROL)
  r"-\}\}": Token(kind: WHITESPACE_CONTROL)
  r"\{\%-": Token(kind: WHITESPACE_CONTROL)
  r"-\%\}": Token(kind: WHITESPACE_CONTROL)

  r"\"\w*\"": Token(kind: STRING_LITERAL, string_value: match[1,-2])
  r"'\w*'": Token(kind: STRING_LITERAL, string_value: match[1,-2])

  r"[a-zA-Z][a-zA-Z0-9-_]*\:": Token(kind: FILTER, filter_name: match[0,-2])

  r"[a-zA-Z][a-zA-Z0-9]*": Token(kind: IDENTIFIER, identifier_name: match)

  r"\d+\.\d+": Token(kind: FLOAT_LITERAL, float_value: parseFloat(match))
  r"\d+": Token(kind: INTEGER_LITERAL, integer_value: parseInt(match))

  r"\|": Token(kind: PIPE)

  # Ignore the normal start and end tags, and whitespace
  # Since we go through the high level parser, we know the type of block anyway
  r"\{\{": continue
  r"\}\}": continue
  r"\s+": continue
```

The only thing I would like is the ability to basically nest the rules for the second lexer under the first. So roughly something like this:
```
makeLexer meta_lexer*[MetaToken]:
  r"\{\{[^}]*\}\}": 
    r"\{\{-": Token(kind: WHITESPACE_CONTROL)
    r"-\}\}": Token(kind: WHITESPACE_CONTROL)
    r"\{\%-": Token(kind: WHITESPACE_CONTROL)
    r"-\%\}": Token(kind: WHITESPACE_CONTROL)

    r"\"\w*\"": Token(kind: STRING_LITERAL, string_value: match[1,-2])
    r"'\w*'": Token(kind: STRING_LITERAL, string_value: match[1,-2])

    r"[a-zA-Z][a-zA-Z0-9-_]*\:": Token(kind: FILTER, filter_name: match[0,-2])

    r"[a-zA-Z][a-zA-Z0-9]*": Token(kind: IDENTIFIER, identifier_name: match)

    r"\d+\.\d+": Token(kind: FLOAT_LITERAL, float_value: parseFloat(match))
    r"\d+": Token(kind: INTEGER_LITERAL, integer_value: parseInt(match))

    r"\|": Token(kind: PIPE)

    # Ignore the normal start and end tags, and whitespace
    # Since we go through the high level parser, we know the type of block anyway
    r"\{\{": continue
    r"\}\}": continue
    r"\s+": continue

  r"\{%[^}]*%\}":
      # Similar thing here

  r"[^{]+": continue
```
But it is mostly a quality of life thing and to allow me to do it all in one lexer/parser pair instead of two. No biggie though 😄

**Comment by d-Pixie** [comment]
I'll give nPEG a read though. It might be a good fit ...

**Comment by choltreppe** [comment]
ah ok, now I got it.
but I probably wont implement that any time soon, since this nested lexing isnt really needed that often, and the 2 lexer solution seems to be just fine.
But feel free to make a PR :)
