### ISSUE TITLE
Error: unhandled exception: value out of range: 256 notin 0 .. 255 [RangeDefect]

### ISSUE THREAD

**Issue by d-Pixie** [choltreppe/parlexgen#3]
Happens in: [/src/parlexgen/private/utils.nim:64,12](https://github.com/choltreppe/parlexgen/blob/main/src/parlexgen/private/utils.nim#L64).

I think this is an overflow of the number of stored patterns? At least it seems to resolve itself if I remove enough cases from this capture `r"(endif|endcase|endfor|endtablerow|endcomment|endraw|endcapture|end)"`, or if I comment out a number of other expressions anywhere in the lexer definition.

Maybe I'm wrong and this is something else, but I don't think it is something I did 🙂

**Comment by choltreppe** [comment]
sorry for responding so late, I didnt check the repo for a while.
the error actually doesnt happen there. That utility function executes some precompiled code at comp-time (which raised the error). But just from that error I can't tell whats the origin of the error. can you share the stack-trace?

**Comment by choltreppe** [comment]
I think I fixed it
